# use rake config website_name="My Portfolio" pass="mypass" dropbox_consumer_secret="XXX" dropbox_consumer_key="XXX"

:test: 
  :website_name: my portfolio test
  :pass: pass
  :dropbox_consumer_key: xxx
  :dropbox_consumer_secret: xxx

:development: 
  :website_name: my portfolio developemnt
  :pass: pass
  :dropbox_consumer_key: xxx
  :dropbox_consumer_secret: xxx
  
:production: 
  :website_name: My Portfolio
  :pass: mypass
  :dropbox_consumer_key: tcjcpjdmtpo089k
  :dropbox_consumer_secret: 14lc8xjqtfhfdrp



